# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: facility.ig
canonical: http://i-tech-uw.github.io/facility-ig
name: FacilityIg
status: draft
version: 0.1.0
fhirVersion: 4.0.1
# copyright:
copyrightYear: 2021+
releaseLabel: ci-build
title: Facility IG
description: |
  Implementation Guide for specifying Facility Registry (FR) 
  requirements and workflows based on the OpenHIE Architecture Version 3 
license: CC-BY-SA-4.0
publisher:
  name: I-TECH-UW
  url: www.github.com/i-tech-uw
  email: pmanko@uw.edu
  contact: Piotr Mankowski
experimental: true
parameters:
  excludettl: true
 
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Functional Specifications: spec.html
  Technical Specifications:
    Artifacts: artifacts.html
dependencies:
  hl7.fhir.uv.ips: 1.0.0
